/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/hKGboTHW7cD
 */
import {
  CollapsibleTrigger,
  CollapsibleContent,
  Collapsible,
} from "@/components/ui/collapsible";
import TechCard from "./tech-card/TechCard";


export default function Faq() {
  return (
    <section className="container mx-auto p-6 py-24">
      <h1 className="text-3xl font-bold mb-4">Frequently Asked Questions</h1>
      <div className="space-y-4">
        <Collapsible className="border rounded-md">
          <CollapsibleTrigger className="flex justify-between items-center p-4 cursor-pointer">
            <h2 className="flex-grow font-semibold">What is OpenAI?</h2>
            <svg
              className=" h-5 w-5 text-gray-500"
              fill="none"
              height="24"
              stroke="currentColor"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              viewBox="0 0 24 24"
              width="24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path d="m6 9 6 6 6-6" />
            </svg>
          </CollapsibleTrigger>
          <CollapsibleContent className="p-4">
            <p>
              OpenAI is an artificial intelligence research lab made up of both
              for-profit and non-profit arms.
            </p>
          </CollapsibleContent>
        </Collapsible>
        <Collapsible className="border rounded-md">
          <CollapsibleTrigger className="flex justify-between items-center p-4 cursor-pointer">
            <h2 className="flex-grow font-semibold">What is GPT-4?</h2>
            <svg
              className=" h-5 w-5 text-gray-500"
              fill="none"
              height="24"
              stroke="currentColor"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              viewBox="0 0 24 24"
              width="24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path d="m6 9 6 6 6-6" />
            </svg>
          </CollapsibleTrigger>
          <CollapsibleContent className="p-4">
            <p>
              GPT-4 is the latest version of OpenAI&apos;s generative
              pre-training transformer, a language prediction model.
            </p>
          </CollapsibleContent>
        </Collapsible>
        <Collapsible className="border rounded-md">
          <CollapsibleTrigger className="flex justify-between items-center p-4 cursor-pointer">
            <h2 className="flex-grow font-semibold">How does ChatGPT work?</h2>
            <svg
              className=" h-5 w-5 text-gray-500"
              fill="none"
              height="24"
              stroke="currentColor"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              viewBox="0 0 24 24"
              width="24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path d="m6 9 6 6 6-6" />
            </svg>
          </CollapsibleTrigger>
          <CollapsibleContent className="p-4">
            <p>
              ChatGPT uses a transformer architecture to generate human-like
              text based on a given input.
            </p>
          </CollapsibleContent>
        </Collapsible>
      </div>
    </section>
  );
}
